#!/usr/bin/env python

import json
from sys import argv

if len(argv) == 1:
   print("Usage: json2txt <input file>")
   print("")
   print("Prints the contents of the json file in a (more) human readable format")
   exit(0)

contents = json.loads(open(argv[1],"r").read())

for key in contents:
    print("{0}: {1}".format(key,contents[key]))
