# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Shared home happiness
export HISTFILE=$HOME/.bash_history.$(hostname)

# User specific environment and startup programs
export EDITOR=vim

PATH=$PATH:$HOME/bin
if [ -d $HOME/.local/bin ];then
   PATH=$PATH:$HOME/.local/bin
fi
export PATH

if [ -f $HOME/.bash_aliases ];then
	. $HOME/.bash_aliases
fi

# Git shell stuff
for git_file in .git-completion.bash .git-prompt.sh;do
	if [[ -f $HOME/${git_file} ]];then
		source $HOME/${git_file}
	fi
done

# Jar library
if [[ -d $HOME/jars ]];then
	export JARS=$HOME/jars
fi

if [[ $(declare -f -F __git_ps1) ]];then
	GIT_PS1_FUNCT='$(__git_ps1 "(%s)")'
fi

# Python stuff
if [[ ! -z $VIRTUALENVS ]];then
activate() {
		source $VIRTUALENVS/$1/bin/activate
}
fi

# Prompt stuff
if [[ -f $HOME/.bash_color ]];then
	source $HOME/.bash_color
fi

PS1="[${BASH_COLOR_START}\D{%s} \h \W ${GIT_PS1_FUNCT}${BASH_COLOR_END}]$ "

